### ISSUE TITLE
Opties bij intersection observer niet verwerkt

### ISSUE THREAD

**Issue by Theo-denBlanken** [HugovanderGeest/Intersection-observer-#1]
```
const opties = {
};
```
Hierdoor zal als je net sectie 3 hebt binnen gescrolled, de de link van sectie 3 worden geactiveerd.  Dat is prima.

Als je dan echter terug scrollt wordt gelijk link sectie 1 gemarkeerd. Dat zou toch van sectie 2 moeten zijn.
Dit komt omdat je de opties niet hebt gedaan: dat object staat leeg. Heb je een hele video overgeslagen??

**Comment by Theo-denBlanken** [comment]
Dag Hugo,

Heb je dit aangepast? Ik zie nog geen commits op GitHub.


Met vriendelijke groeten,

--

[ma-logo]
Theo den Blanken

[Theo]<http://blanken5.home.xs4all.nl/>
docent
Mediadeveloper
Mediacollege Amsterdam
[Twitter]<https://twitter.com/theodenblanken/> [WordPress] <http://bla.hosts.ma-cloud.nl/>


Van: Hugo van der Geest <notifications@github.com>
Datum: vrijdag, 15 januari 2021 om 12:27
Aan: HugovanderGeest/Intersection-observer- <Intersection-observer-@noreply.github.com>
CC: Theo den Blanken <T.denBlanken@ma-web.nl>, Author <author@noreply.github.com>
Onderwerp: Re: [HugovanderGeest/Intersection-observer-] Opties bij intersection observer niet verwerkt (#1)

Closed #1<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FHugovanderGeest%2FIntersection-observer-%2Fissues%2F1&data=04%7C01%7Ct.denblanken%40ma-web.nl%7C19f781877d4944a224bc08d8b9489570%7C8e600f9230df4667b7c03f2595f3f12b%7C0%7C0%7C637463068687150610%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=XNXGtpUJfF1tLD5SPUSIS1e37RqK7Xz2OskR0QlmO84%3D&reserved=0>.

**Comment by HugovanderGeest** [comment]
Ja, maar ik zie nu dat het niet doorgekomen is, ik ga het even uitzoeken

Met vriendelijke groet,
Hugo van der Geest
Van: Theo den Blanken<mailto:notifications@github.com>
Verzonden: zaterdag 16 januari 2021 17:42
Aan: HugovanderGeest/Intersection-observer-<mailto:Intersection-observer-@noreply.github.com>
CC: Hugo van der Geest<mailto:Hugo.vdg@outlook.com>; State change<mailto:state_change@noreply.github.com>
Onderwerp: Re: [HugovanderGeest/Intersection-observer-] Opties bij intersection observer niet verwerkt (#1)

Dag Hugo,

Heb je dit aangepast? Ik zie nog geen commits op GitHub.


Met vriendelijke groeten,

--

[ma-logo]
Theo den Blanken

[Theo]<http://blanken5.home.xs4all.nl/>
docent
Mediadeveloper
Mediacollege Amsterdam
[Twitter]<https://twitter.com/theodenblanken/> [WordPress] <http://bla.hosts.ma-cloud.nl/>


Van: Hugo van der Geest <notifications@github.com>
Datum: vrijdag, 15 januari 2021 om 12:27
Aan: HugovanderGeest/Intersection-observer- <Intersection-observer-@noreply.github.com>
CC: Theo den Blanken <T.denBlanken@ma-web.nl>, Author <author@noreply.github.com>
Onderwerp: Re: [HugovanderGeest/Intersection-observer-] Opties bij intersection observer niet verwerkt (#1)

Closed #1<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FHugovanderGeest%2FIntersection-observer-%2Fissues%2F1&data=04%7C01%7Ct.denblanken%40ma-web.nl%7C19f781877d4944a224bc08d8b9489570%7C8e600f9230df4667b7c03f2595f3f12b%7C0%7C0%7C637463068687150610%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=XNXGtpUJfF1tLD5SPUSIS1e37RqK7Xz2OskR0QlmO84%3D&reserved=0>.
